//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YashProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimInfoMst
    {
        public int Dim_ID { get; set; }
        public string Dim_type { get; set; }
        public string Dim_SubType { get; set; }
        public string Dim_Crt { get; set; }
        public string Dim_Price { get; set; }
        public string Dim_Img { get; set; }
    }
}
