//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YashProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inquiry
    {
        public int ID { get; set; }
        public string C_Name { get; set; }
        public string City { get; set; }
        public string Contact { get; set; }
        public string EmailID { get; set; }
        public string Comment { get; set; }
        public System.DateTime CDate { get; set; }
    }
}
