//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YashProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegMst
    {
        public int UserID { get; set; }
        public string UserFName { get; set; }
        public string UserLNAme { get; set; }
        public string C_Address { get; set; }
        public string City { get; set; }
        public string C_State { get; set; }
        public string Mob_No { get; set; }
        public string Email_ID { get; set; }
        public string Dob { get; set; }
        public string C_Date { get; set; }
        public string C_Password { get; set; }
    }
}
